version: "3.9"

services:
  commit-bot:
    build: .
    container_name: commit-bot

    volumes:
      - .:/app

    environment:
      - PYTHONUNBUFFERED=1

    working_dir: /app

    command: python -m app.main

    restart: unless-stopped